config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 3, maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully edited."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted."
    redirect_to articles_path
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
  
  def set_article
    @article = Article.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role:"form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Article's Title", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article's Body" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: "btn btn-primary btn-lg" %>
            </div>
        </div>
        <% end %>
    </div>
    <div class="col-xs-4 col-xs-offset-4">
        <%= link_to "Cancel and Go Back", articles_path %>
    </div>
</div>

app/views/articles/edit.html.erb
<div class="container main-content">
    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <h1>Editing Article id <%= @article.id %></h1>
        </div>
    </div>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container main-content">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <h1 align="center">Blog</h1>
            <p><%= link_to "Add a new Article", new_article_path %></p>
            <% @articles.each do |a| %>
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to a.title, article_path(a) %>
                </div>
                <div class="article-body">
                    <%= truncate(a.description, length: 100) %>
                </div>
                <div class="article-actions">
                    <%= link_to "Edit", edit_article_path(a), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Delete", article_path(a), method: :delete,
                                        data: { confirm: "Are you sure?" },
                                        class: "btn btn-xs btn-danger" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class="container main-content">
    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <h1>Create an Article</h1>
        </div>
    </div>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container main-content">
    <%= render "shared/errors", obj: @article %>
    <h2 align="center"><%= @article.title %></h2>
    <div class="well col-xs-8 col-xs-offset-2">
        <%= simple_format(@article.description) %>
        <div class="article-actions">
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(@article), method: :delete,
                                data: { confirm: "Are you sure?" },
                                class: "btn btn-xs btn-danger" %>
            <%= link_to "Back to Blog", articles_path, class: "btn btn-xs btn-success" %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>Santiago
                        <br>Chile</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="http://www.facebook.com/gjacuna" class="btn-social btn-outline"><span class="sr-only">Facebook</span><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="http://www.twitter.com/gjacuna" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="http://cl.linkedin.com/in/gjacuna" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="mailto:g@acuna.me" class="btn-social btn-outline"><span class="sr-only">Google Plus</span><i class="fa fa-fw fa-send"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About Guillermo</h3>
                    <p>Bilingual entrepreneur, cofounder of the largest marketplace-lending platform in Latin America, <a href="http://cumplo.cl">Cumplo</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; <a href="http://acuna.me">acuna.me</a> 2017
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dimiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Guillermo Acuña Kitto", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Blog", articles_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GakBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container main-content">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>About</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <p>Hello</p>
            <p>I'm a cofounder of <a href="http://cumplo.cl" target="_new">Cumplo</a>, the largest marketplace lending platform in Latin America..</p>
            <p>I believe in many things, some of which can be read on the blog entries, but my conviction is the world can be changed for the better. It just takes a little <span>Team Work</span>.</p>
            <p>Before Cumplo I worked for the Chilean government, where I realized changing the world is not that easy when you're a bureaucrat, and a Chilean investment bank, where I learned finance and technology are powerful tools that should be used for good.</p>
            <p>I have been a guest speaker at many events, most importantly for <a href="http://www.asech.cl/" target="_new">ASECH</a>; I have mentored startups and students; and I have been a teacher, with the most formal experience as a teacher of IT Engineering at <a href="http://www.duoc.cl" target="_new">Duoc</a>, in Chile.</p>
    		<p>I also cofounded 2 software companies as side projects, focused on providing technological solutions for SMEs. RIP Huntme and Koywe.</p>
    		<p>Feel free to contact me whenever you want.</p>
        </div>
    <!--
        <div class="col-lg-8 col-lg-offset-2 text-center">
            <a href="#" class="btn btn-lg btn-outline">
                <i class="fa fa-download"></i> Download Theme
            </a>
        </div>
    -->
    </div>
</div>

app/views/pages/home.html.erb
<div class="cointainer-fluid">
    <div class="home-header row">
        <div class="col-lg-12">
            <%= image_tag "gak.png", class: "img-responsive img-circle" %>
            <div class="intro-text">
                <h1 class="name">Guillermo Acuña Kitto</h1>
                <span class="skills">Always under construction. All-around janitor, bilingual cofounder.</span>
            </div>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">We had <%= pluralize(obj.errors.count, "error") %> trying to add the new article:</h2>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                  <% obj.errors.full_messages.each do |msg| %>
                    <li class="list-group-item"><%= msg %></li>
                  <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>
<% end %>